In [1]:
import pandas as pd
#16년도
# def datetimepro16(df):
#     df['time'] = pd.date_range(start='2016-01-01-00', end='2016-12-31-23', freq = 'H')
#     df["datetime-year"] = df["time"].dt.year
#     df["month"] = df["time"].dt.month
#     df["day"] = df["time"].dt.day
#     df["hour"] = df["time"].dt.hour
#     df = df[['datetime-year', 'month', 'day', 'hour', 'CO','CO2','NO2','PM2.5','PM10']]
#     df.replace('중단', 0, inplace = True)
#     df.replace('동불',0, inplace = True)
#     df.replace('전단', 0, inplace = True)
#     df.replace('점검', 0, inplace = True)
#     df[['CO','CO2','NO2','PM2.5','PM10']].astype(float)
#     return df
#15년도
def datetimepro15(df):
    df['time'] = pd.date_range(start='2015-01-01-00', end='2015-12-31-23', freq = 'H')
    df["datetime-year"] = df["time"].dt.year
    df["month"] = df["time"].dt.month
    df["day"] = df["time"].dt.day
    df["hour"] = df["time"].dt.hour
    df = df[['datetime-year', 'month', 'day', 'hour', 'CO','CO2','NO2','PM2.5','PM10','HCHO']]
    df.replace('중단', 0, inplace = True)
    df.replace('동불',0, inplace = True)
    df.replace('전단', 0, inplace = True)
    df.replace('점검', 0, inplace = True)
    df[['CO','CO2','NO2','PM2.5','PM10']].astype(float)
    return df
#14년도
def datetimepro14(df):
    df['time'] = pd.date_range(start='2014-01-01-00', end='2014-12-31-23', freq = 'H')
    df["datetime-year"] = df["time"].dt.year
    df["month"] = df["time"].dt.month
    df["day"] = df["time"].dt.day
    df["hour"] = df["time"].dt.hour
    df = df[['datetime-year', 'month', 'day', 'hour', 'CO','CO2','NO2','PM2.5','PM10','HCHO']]
    df.replace('중단', 0, inplace = True)
    df.replace('동불',0, inplace = True)
    df.replace('전단', 0, inplace = True)
    df.replace('점검', 0, inplace = True)
    df[['CO','CO2','NO2','PM2.5','PM10']].astype(float)
    return df

In [4]:
남포__16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/남포__16.csv',encoding='cp949')
# 사상__16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/사상16.csv',encoding='cp949')
# 서면1p16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면1p16.csv',encoding='cp949')
# 서면1w16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면1w16.csv',encoding='cp949')
# 서면2p16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면2p16.csv',encoding='cp949')
# 서면2w16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면2w16.csv',encoding='cp949')
# 남포__15 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/남포15.csv',encoding='cp949')
# 사상__15 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/사상15.csv',encoding='cp949')
# 서면1p15 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면1p15.csv',encoding='cp949')
# 서면1w15 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면1w15.csv',encoding='cp949')
# 서면2p15 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면2p15.csv',encoding='cp949')
# 서면2w15 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면2w15.csv',encoding='cp949')
# 남포__14 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/남포14.csv',encoding='cp949')
# 사상__14 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/사상14.csv',encoding='cp949')
# 서면1p14 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면1p14.csv',encoding='cp949')
# 서면1w14 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면1w14.csv',encoding='cp949')
# 서면2p14 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면2p14.csv',encoding='cp949')
# 서면2w14 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면2w14.csv',encoding='cp949')
남포__16

,Unnamed: 0,datetime-year,month,day,hour,CO,CO2,NO2,PM2.5,PM10,HCHO
0,0,2016,1,1,0,0.5,500.0,0.039,55.0,61.0,2.9
1,1,2016,1,1,1,0.4,461.0,0.036,49.0,83.0,3.2
2,2,2016,1,1,2,0.3,433.0,0.027,33.0,55.0,0.4
3,3,2016,1,1,3,0.3,422.0,0.019,28.0,47.0,1.9
4,4,2016,1,1,4,0.3,424.0,0.020,40.0,47.0,2.8
...,...,...,...,...,...,...,...,...,...,...,...
8779,8779,2016,12,31,19,0.6,739.0,0.049,27.0,48.0,6.8
8780,8780,2016,12,31,20,0.6,731.0,0.044,35.0,42.0,3.5
8781,8781,2016,12,31,21,0.7,670.0,0.045,30.0,44.0,2.9
8782,8782,2016,12,31,22,0.6,676.0,0.042,35.0,40.0,2.9
8783,8783,2016,12,31,23,0.6,677.0,0.040,32.0,37.0,3.1

In [27]:
lis = [남포__16,
사상__16,
서면1p16,
서면1w16,
서면2p16,
서면2w16,
남포__15,
사상__15,
서면1p15,
서면1w15,
서면2p15,
서면2w15,
남포__14,
사상__14,
서면1p14,
서면1w14,
서면2p14,
서면2w14]

# for i in range(0,6):
#     lis[i] = datetimepro16(lis[i])
for i in range(6,12):
    lis[i] = datetimepro15(lis[i])
for i in range(14,18):
    lis[i] = datetimepro14(lis[i])
    
# lis[0].to_csv('시계열/남포__16.csv')
# lis[1].to_csv('시계열/사상__16.csv')
# lis[2].to_csv('시계열/서면1p16.csv')
# lis[3].to_csv('시계열/서면1w16.csv')
# lis[4].to_csv('시계열/서면2p16.csv')
# lis[5].to_csv('시계열/서면2w16.csv')
lis[6].to_csv('시계열/남포__15.csv')
lis[7].to_csv('시계열/사상__15.csv')
lis[8].to_csv('시계열/서면1p15.csv')
lis[9].to_csv('시계열/서면1w15.csv')
lis[10].to_csv('시계열/서면2p15.csv')
lis[11].to_csv('시계열/서면2w15.csv')
# lis[12].to_csv('시계열/남포__14.csv')
# lis[13].to_csv('시계열/사상__14.csv')
lis[14].to_csv('시계열/서면1p14.csv')
lis[15].to_csv('시계열/서면1w14.csv')
lis[16].to_csv('시계열/서면2p14.csv')
lis[17].to_csv('시계열/서면2w14.csv')

In [51]:
# 남포__16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/남포16.csv',encoding='cp949')
# 사상__16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/사상16.csv',encoding='cp949')
서면1p16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면1p16.csv',encoding='cp949')
서면1w16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면1w16.csv',encoding='cp949')
서면2p16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면2p16.csv',encoding='cp949')
# 서면2w16 = pd.read_csv('C:/Users/User/jupyternotebook/LAB/시계열/서면2w16.csv',encoding='cp949')

In [34]:
def datetimepro16(df):
    df['time'] = pd.date_range(start='2016-01-01-00', end='2016-12-31-23', freq = 'H')
    df["datetime-year"] = df["time"].dt.year
    df["month"] = df["time"].dt.month
    df["day"] = df["time"].dt.day
    df["hour"] = df["time"].dt.hour
    df = df[['datetime-year', 'month', 'day', 'hour', 'CO','CO2','NO2','PM2.5','PM10','HCHO']]
    df.replace('중단', 0, inplace = True)
    df.replace('동불',0, inplace = True)
    df.replace('전단', 0, inplace = True)
    df.replace('점검', 0, inplace = True)
    df[['CO','CO2','NO2','PM2.5','PM10','HCHO']].astype(float)
    return df

lis = [남포__16,
사상__16,
# 서면1p16,
# 서면1w16,
# 서면2p16,
서면2w16]

for i in range(0,3):
    lis[i] = datetimepro16(lis[i])

    
lis[0].to_csv('시계열/남포__16.csv')
lis[1].to_csv('시계열/사상__16.csv')
lis[2].to_csv('시계열/서면2w162.csv')
# to_csv('시계열/서면1p16.csv')
# lis[3].to_csv('시계열/서면1w16.csv')
# lis[4].to_csv('시계열/서면2p16.csv')
# lis[5].to_csv('시계열/서면2w16.csv')

In [52]:
def datetimepro16(df):
    df['time'] = pd.date_range(start='2016-01-01-00', end='2016-12-31-23', freq = 'H')
    df["datetime-year"] = df["time"].dt.year
    df["month"] = df["time"].dt.month
    df["day"] = df["time"].dt.day
    df["hour"] = df["time"].dt.hour
    df = df[['datetime-year', 'month', 'day', 'hour', 'CO','CO2','NO2','PM2.5','PM10']]
    df.replace('중단', 0, inplace = True)
    df.replace('동불',0, inplace = True)
    df.replace('전단', 0, inplace = True)
    df.replace('점검', 0, inplace = True)
    df[['CO','CO2','NO2','PM2.5','PM10']].astype(float)
    return df


lis = [서면1p16,
서면1w16,
서면2p16]


for i in range(0,3):
    lis[i] = datetimepro16(lis[i])

    
# lis[0].to_csv('시계열/남포__16.csv')
# lis[1].to_csv('시계열/사상__16.csv')
# lis[2].to_csv('시계열/서면2w162.csv')
lis[0].to_csv('시계열/서면1p16.csv')
lis[1].to_csv('시계열/서면1w16.csv')
lis[2].to_csv('시계열/서면2p16.csv')
# lis[0].to_csv('시계열/서면1p16.csv')
# lis[0].to_csv('시계열/서면2p16.csv')